
name: Run ci/cd tets

on:
  push:
    branches:
      - master

jobs:

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, zip, exif, pcntl, gd, opcache, mbstring

      - name: copy from .env.example to .env
        run: cp .env.example .env

      - name: generate app key
        run: php artisan key:generate
