
name: Run ci/cd tets

on:
  push:
    branches:
      - master

jobs:

  pre-build:
    name: Pre Build

    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, zip, exif, pcntl, gd, opcache, mbstring

      - name: copy from .env.example to .env
        run: cp .env.example .env

      - name: Run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{env.COMPOSER_VERSION}}
          command: install

      - name: generate app key
        run: php artisan key:generate

  build:

    name: Build

    needs: pre-build

    steps:
      - name: Run phpunit
        run: ./vendor/bin/phpunit
